workflows:
  build-ios:
    name: Build iOS app
    max_build_duration: 60
    environment:
      node: 16.20.0
      xcode: latest
      cocoapods: default
      vars:
        NODE_ENV: production
    scripts:
      - name: Instalar dependências
        script: |
          npm install
          cd ios
          pod install
      - name: Build iOS
        script: |
          xcodebuild -workspace ios/SeuApp.xcworkspace -scheme SeuApp -sdk iphoneos -configuration Release
    artifacts:
      - ios/build/**/*.app


