workflows:
  ios-capacitor-build:
    name: Build iOS app with Capacitor
    environment:
      node: 18.20.0
      xcode: latest
    scripts:
      - name: Instalar dependências
        script: |
          npm install
          npx cap sync ios
          cd ios
          pod install
      - name: Build iOS
        script: |
          cd ios
          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -sdk iphoneos \
                     -configuration Release \
                     -derivedDataPath build
    artifacts:
      - ios/build/Build/Products/Release-iphoneos/*.app
    publishing:
      email:
        recipients:
          - adiliofkis@gmail.com
