workflows:
  ios-capacitor-build:
    name: Build iOS app with Capacitor
    environment:
      node: 18.20.0
      xcode: latest
    scripts:
      - name: Instalar dependências
        script: |
          npm install
          npx cap sync ios
          cd ios
          pod install
      - name: Controle Pessoal
        script: |
          xcodebuild -workspace App.xcworkspace -scheme App -sdk iphoneos -configuration Release
    artifacts:
      - ios/build/**/*.app
    publishing:
      email:
        recipients:
          - adiliofkis@gmail.com




