workflows:
  ios-capacitor-build:
    name: Build iOS app with Capacitor
    environment:
      node: 20 # Usando uma versão LTS do Node.js
      xcode: latest
      cocoapods: default
    scripts:
      - name: Instalar dependências
        script: |
          npm install
      - name: Build do App Web e Sincronização com Capacitor
        script: |
          npm run build:mobile
      - name: Instalar dependências do iOS (CocoaPods)
        script: |
          cd ios/App && pod install && cd ../..
      - name: Build do App iOS
        script: |
          # NOTA: Este passo requer que a assinatura de código esteja configurada no Codemagic.
          # Você precisará fazer upload de seus certificados e perfis de provisionamento.
          xcodebuild -workspace ios/App/App.xcworkspace \
                     -scheme App \
                     -sdk iphoneos \
                     -configuration Release \
                     -allowProvisioningUpdates \
                     archive \
                     -archivePath $CM_BUILD_DIR/FluxoFinanceiro.xcarchive \
                     # -Passe seu team id aqui CODE_SIGN_IDENTITY="..." DEVELOPMENT_TEAM="..."

          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/FluxoFinanceiro.xcarchive \
                     -exportPath $CM_BUILD_DIR/build/ios \
                     -exportOptionsPlist $CM_BUILD_DIR/ios/App/exportOptions.plist
    artifacts:
      - $CM_BUILD_DIR/build/ios/*.ipa
    publishing:
      email:
        recipients:
          - adiliofkis@gmail.com
